# 2.1 四則演算

2.1.1 四則演算の利用

In [1]:
1 + 2

3

In [2]:
(1 + 2 * 3 - 4) / 5

0.6

2.1.2 累乗

累乗は**を使って表す

In [3]:
2**8

256

# 2.2 変数

2.2.1 変数を利用した計算

In [4]:
x = 1
y = 1/3
x + y

1.3333333333333333

2.2.2 変数名の表記

変数名にはアルファベットや数字、アンダースコア_を使うことが出来る。
ただし、変数名のはじめの文字には数字は使えない。

In [5]:
Data_1 = 1/5
Data_2 = 3/5
Data_1 + Data_2

0.8

# 2.3 型

2.3.1 型の種類

型＝データの種類のこと

2.3.2 型の調査

整数はint型が使われる

In [6]:
type(100)

int

小数点を持つ実数はfloat型が使われる

In [7]:
type(100.1)

float

In [8]:
x = 100
type(x)

int

In [9]:
x = 100.1
type(x)

float

2.3.3 文字列

文字列を扱うにはstr型が使われる

In [10]:
x = 'learning'
type(x)

str

上記のように、'(シングルクォーテーション)や ''(ダブルクォーテーション)で囲むことで文字列として認識される。

# 2.4 print 文

2.4.1 print 文の利用

In [11]:
x = 1/3
x
y = 2/3
y

0.6666666666666666

最後の行に限らず変数を表示したい場合には、printを使う。

In [12]:
x = 1/3
print(x)
y = 2/3
print(y)

0.3333333333333333
0.6666666666666666


2.4.2 文字列と組み合わせた数値の表示1

文字列と組み合わせて表示したい場合には、例えば以下のコマンドで表示する。

In [13]:
print('x= ' + str(x))

x= 0.3333333333333333


文字を表示したいときはstrを使う

上記のstr(x)は、float型のxをstr型に変換する。そして、'x=' + str(x)によって、2つのstr型が連結される。''+''はint型やfloat型だと足し算の意味になるが、str型では連結として働く。

2.4.3 文字列と組み合わせた数値の表示2

文字列と組み合わせる別の方法として、formatも便利である。

In [14]:
print('weight = {0} kg'.format(x))

weight = 0.3333333333333333 kg


変数を文字で挟みたいときはformatを使う

print()の中は、'文字列'.format(x)となっているが、これは「文字列の中の{0}の部分をxの中身で置き換える」という意味である。'文字列'とformat(x)の間に''.''があることに注意せよ。

複数の変数を表示したい場合には、文字列中に{0}、{1}、{2}で指定する。

In [15]:
x = 1/3
y = 1/7
z = 1/4
print('weight: {0} kg, {1} kg, {2} kg'.format(x,y,z))

weight: 0.3333333333333333 kg, 0.14285714285714285 kg, 0.25 kg


{数値 :.nf}とすれば、小数点以下n桁までの表示になる。例えば、float型の小数点以下2桁まで表示したい場合には、{通し番号 :.2f}とする。

In [16]:
print('weight: x={0:.2f} kg, y={1:.2f} kg, z={2:.2f} kg'.format(x,y,z))

weight: x=0.33 kg, y=0.14 kg, z=0.25 kg


# 2.5 list(リスト、配列変数）

2.5.1 listの利用

数のデータを1つのまとまりとして扱いたい、つまり、配列変数を使い場合には
list(リスト)型を使います。listは、 []を使ってます。

In [17]:
x = [1, 1, 2, 3, 5] #listの定義
print(x) #表示

[1, 1, 2, 3, 5]


各成分は ×[要素番号]で参照する(見る)ことができる。Pythonでは、配列の要素番号(インデックス)は0から始まる。

In [18]:
x[0]

1

In [19]:
x[4]

5

以下のように入力すると、×はlist型、×[]はint型であることがわかる。

In [20]:
print(type(x))
print(type(x[0]))

<class 'list'>
<class 'int'>


つまり、×は、int型から構成されるlist型だと理解できる。list型は、str型でも作ることが出来る。また、以下のように異なる型を混在させることもできる。

In [21]:
s=['SUN', 1, 'MON', 2]
print(type(s[0]))
print(type(s[3]))

<class 'str'>
<class 'int'>


2.5.2 2次元の配列

その他、list型の更にlist型を作ることで、2次元の配列を作ることもできる。

In [22]:
a=[[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


以下のコードのように、要素の参照は、変数名[i][j]のようにする。

In [23]:
a=[[1, 2, 3], [4, 5, 6]]
print(a[1][2])

6


3次元配列、4次元配列も入れ子の深さを増やして作ることができる。listの要素の書き換えは、×[要素番号]=書き換える数値で行える。

In [24]:
x=[1, 1, 2, 3, 5]
x[3]=100
print(x)

[1, 1, 2, 100, 5]


2.5.3 listの長さ

listの長さは、lenで調べることができる。

In [25]:
x=[1, 1, 2, 3, 5]
len(x)

5

2.5.4 連続した整数のデータの作成

5から9までなど、連続した整数のデータを作るには、range(はじめの数,終わりの数+1)を使う。

In [26]:
y = range(2,10)
print(y[0], y[1], y[2], y[3], y[4], y[6])

2 3 4 5 6 8


yはlist型に似ているが、実は少し違う。range型と呼ばれるメモリ―を節約した形のデータ型なのである。yそのものを表示させると、次のようになり、[5,6,7,8,9] と表示されない。

In [27]:
print(y)

range(2, 10)


range型は、list型と同様な方法で要素を参照することができるが、要素を書き換えることはできません。例えば、range型に対してy[2]=2とするとエラーが出る。
range型はlistを使って要素が書き換えられるlist型に変換することができる。

In [28]:
z=list(range(5,10))
print(z)

[5, 6, 7, 8, 9]


はじめの数を省略して、range(終わりの数+1)とすると、0から始まる数列になる。

In [29]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# 2.6 tuple (タプル)

2.6.1 tupleの利用

配列を表す型に、list型に加えてtuple型という配列変数なるものがあります。tupleはlistとは異なり要素を書き換えることはできないです。tuple型は、(1,2,3)などと、()を使って配列を表します。

In [30]:
a=(1, 2, 3)
print(a)

(1, 2, 3)


2.6.2 要素の参照

要素の参照は、list型と同様です。

In [31]:
a[1]

2

参照には()ではなく、list型と同様に[]を使うことに注意してください。tupleは書き換えができないので、a[1]=2などとするとエラーが出ます。それでは、listとtupleはどう使い分けされているのでしょうか?
とりあえず、自分で定義するときには、書き換えが可能なlist型を使っていれば間違いがないのですが、後ほど説明する「関数」の出力が複数ある場合は、自動的にtuple としてまとめられます。また、既存の関数の入力がtupleで指定されている場合もあります。
list型とtuple型を間違えてエラーが出ることが多々ありますので、違いを気にするようにしましょう。これもtype()で知ることができます。

In [32]:
type(a)

tuple

2.6.3 長さが1のtuple

ところで、(1,2)はタプルですが、(1)はtupleでしょうか。これはtupleではありません。()は、演算の順番を表す普通の括弧としてみなされます。長さが1のtupleは(1,)と","を付けて区別します。

In [33]:
a = (1)
type(a)

int

In [34]:
a = (1,)
type(a)

tuple

# 2.7 if文

2.7.1 if文の利用

プログラムの処理の流れを様々な条件で分岐させるためにif文を使います。例えば、
以下のようにすれば、はじめの行で×=11と代入しているので、iのx>10が真値
値(True)となり、4マス右にずれている (インデントされているが(A1と行
A2)、すべて実行されます。

In [35]:
x = 10
if x >= 10:
    print('x is 10 or more')
else:
    print('x is less than 10')

x is 10 or more


インデントがif文以下のまとまりを示すということです。このようにPythonではイ
ンデントに重要な意味がありますので注意が必要です。ちなみに"#...(A
1)"はコメント文です。#を使うとその後は、実行では無れます。視最さ
初の行を×-9と書き換えれば、ifのx>10が偽值(Falsなるので、e)と
lse:の後のprint('x is sma ler  th'an11)がます。実ところで行され
、ifの後に続く"×>10"は、TrueかFalseの値をとるのデータool型
です。そのまま打ち込めば、以下のように値できます。とがで 33

In [36]:
x > 10

False

また以下のようにすれば、×>10という演算の結果の型がbool型だということがわかります。

In [37]:
type(x > 10)

bool

if の右に書かれたbool型がTrueであれば、次の行から始まるインデントされた
ブロックが実行され、False であればelse:以降でインデントされたブロックが実
されるということになります。else:は省略することもできます。

2.7.2 比較演算子

">"を比較演算子と呼びますが、if文で使う比較演算子をまとめると、表2.2の
ようになります。これらの演算の結果はすべてbool型となります
表2.2:比較演算子
比較演算子 内容
a ==b aとbが等しい
 >b
aがbより大きい
aがb 以上 a >=b
aがbより小さい a<b
 aがb 以下
a <=b
aとbは条件なる a!=b
牛文を重ねたい場合にはo、and(かつ)や。r(まえば、「10 <= x と x <= 20ます。例
<<=20 が同時に満たされたとき」、とには、それう条件を使いたい場合
らをandでつなげます。。

In [38]:
x = 15
if 10 <= x and x <= 20:
    print('x is between 10 and 20.')

x is between 10 and 20.


In [39]:
x = 15
if 10 <= x <= 20:
    print('x is between 10 and 20.')
elif x < 10:
    print('x is less than 10.')
elif 20 < x:
    print('x is more than 20.')

x is between 10 and 20.


# 2.8 for文

2.8.1 for文の利用

演算を繰り返すには、for文を使います。

In [40]:
for i in [1, 2, 3]:
    print(i)

1
2
3


for文は、for"変数"in"list型:という形となっています。listの要素の数だけfor文以下のインデントされている行が実行されます。繰り返すたびにlistの要素が順番に"変数"に入ります。list型の代わりに、tuple型range型を使うこともできます。
実践的な例として、list型の変数(num)の要素をすべて2倍にしたい場合は、for文を使って以下のように記述できます。

In [41]:
num = [2, 4, 6, 8, 10]
for i in range(len(num)):
    num[i] = num[i] * 2
print(num)

[4, 8, 12, 16, 20]


In [42]:
num = [1, 3, 5, 7, 9]
for i in range(len(num)):
    num[i] = num[i] * 2
print(num)

[2, 6, 10, 14, 18]


for i in range(len(num))とすることで、1を0からnumの要素数分-1まで変化させ、num[i]の中身を順に書き換えています。

2.8.2 enumerateの利用

前述と同じ機能を、Pythonではenumerate を使って、以下のようにエレガントに
記述できます。

In [43]:
num = [2, 4, 6, 8, 10]
for i, n in enumerate(num):
    num[i] = n * 2
print(num)

[4, 8, 12, 16, 20]


上記のようにすると、numのindexと num[index]の値が、iとnに入るのです。
しかし本書では、多言語を学んできた方にもわかりやすいように、enumerateを使わない記法で統します。

# 2.9 ベクトル

ベクトルの数学的な意味は第4章で説明しますので、ここでは、2
honのベクトルの扱い方を解説します。まず、list型はベクトルとして使うことができるのでしょうか。例別えば、[1,2]+[3,4]と入力したら、[4,6]のようなえが返ってくるのでしょうか？.
もnp
くるのでしょうか?実験してみましょう。

In [44]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [45]:
[1, 3] + [3, 5]

[1, 3, 3, 5]

答えは予測とは異なりました。list型は"+演算子"を連結として解釈するのです。str型のときと同じです。

2.9.1 numpyの利用

pythonで、ベクトルや行列を表すには、numpy(ナンパイ)というライブラリを読み込んで機能を拡張します。
pytohnでは、様々なライブラリが開発されており、importで簡単に読み込むことができます。行列演算をするためのライブラリnumpyは以下のようにimportします。

In [46]:
import numpy as np

In [47]:
import numpy as np

シンプルですね。as npの部分は、numpyをnpと省略して使うという意味です。
ここはユーザーが好きなように決められますので、例えばnpではなく、npyとしても問題ありません。
しかし、numpyの場合、慣習的にrp とする場合が通例となっていますので本書でもnpとします。以降、numpyの機能は、np."function"という形で呼び出すことができます。

2.9.2 ベクトルの定義

べクトル(1次元配列)は、np.array(1ist型)で定義します。

In [48]:
x=np.array([1, 2, 3])
x

array([1, 2, 3])

In [49]:
x = np.array([2, 4, 6])
print(x)

[2 4 6]


ちなみに、×をprint(×)で表示させると、以下のように要素の間の","が省略され、すっきりとした表示となります。

In [50]:
print(x)

[2 4 6]


一方、np.array型ではなくlistをprintすると要素間の","は残ります。
さて、×がベクトルであることを確認するために、yも定義して、先ほど定義したxと足してみると、以下のように表示され、×とyがベクトルとして扱われていることが確認できました。

In [51]:
y=np.array([4, 5, 6])
print(x + y)

[ 6  9 12]


In [52]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? 
Nothing done.


In [53]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)

[5 7 9]


type(×)をすると、以下のようになることから、xはnumpy.ndarray型であることがわかります。本書ではこれ以降省略してndarray型と呼ぶことにします。

In [54]:
type(x)

numpy.ndarray

2.9.3 要素の参照

1つの要素を参照するには、list型と同様に[]を使います。

In [55]:
x[0]

1

2.9.4 要素の書き換え

要素を書き換えるには、×[書き換えたい要素番号]=数値とします。

In [56]:
x[0] = 100
print(x)

[100   2   3]


In [57]:
x = np.array([1, 2, 3])
x[0] = 10
x[1] = 20
x[2] = 30
print(x)

[10 20 30]


2.9.5 連続した整数のベクトルの作成

要素の値が1ずつ増えていくベクトル配列は、np.arange(n)で作れます。list型の配列を出力するrange(n)と同様に、0からn-1まの配列が生成できます。
arange(n1,n2)とすれば、n1からn2-1までの配列になります。

In [58]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [59]:
print(np.arange(20))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [60]:
print(np.arange(5, 10))

[5 6 7 8 9]


In [61]:
print(np.arange(10,20))

[10 11 12 13 14 15 16 17 18 19]


ndarray型は、list型と似て、for文のlistの代わりに使うこともできますが、ベクトル演算が可能という点で異なります。

2.9.6 ndarray型の注意点

ndarray型を使うに当たってとても重要なことがあります。ndarray型の中身をコピーするに
は、通常の変数のようにb=aではなく、b=a.copy()とないといけま
せん。単にb=aとすると、aの内容の保存先の参照が渡されます。ややこし、
いのです=が、baとした後でbの内容を変更すると、その変にも反映されてしまうのです。例えば、以下のように、aの内容は修正していないのに、aが
bと同じ値になっていますなります。

In [62]:
a = np.array([1, 1])
b = a
print('a =' + str(a))
print('b =' + str(b))
b[0] = 100
print('b =' + str(b))
print('a =' + str(a))

a =[1 1]
b =[1 1]
b =[100   1]
a =[100   1]


In [63]:
a = np.array([1, 2])
b = a
print('a =' + str(a))
print('b =' + str(b))
b[0] = 10
b[1] = 20
print('a =' + str(a))
print('b =' + str(b))

a =[1 2]
b =[1 2]
a =[10 20]
b =[10 20]


これを、b- a.copy()とすれば、bはaから独立した変数として扱われます。

In [64]:
a = np.array([1, 1])
b = a.copy()
print('a =' + str(a))
print('b =' + str(b))
b[0] = 100
print('b =' + str(b))
print('a =' + str(a))

a =[1 1]
b =[1 1]
b =[100   1]
a =[1 1]


In [65]:
a = np.array([1, 2])
b = a
b = a.copy()
print('a =' + str(a))
print('b =' + str(b))
b[0] = 10
b[1] = 20
print('a =' + str(a))
print('b =' + str(b))

a =[1 2]
b =[1 2]
a =[1 2]
b =[10 20]


# 2.10 行列

2.10.1 行列の定義

行列は、ndarrayの2次元配列として以下のようにして定義できます。

In [66]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [67]:
x = np.array([[1, 3, 5], [2, 4, 6]])
print(x)

[[1 3 5]
 [2 4 6]]


2.10.2 行列のサイズ

行列(配列)のサイズは、ndarray型の変数名,shapeで知ることができます。

In [68]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.shape

(2, 3)

この出力は()で囲まれているのでtupple型とわかります。この場合、以下のようにすれば、wとhに、それぞれ2と3を格納することができます。

In [69]:
w, h = x.shape
print(w)
print(h)

2
3


2.10.3 要素の参照

要素の参照は、以下のように次元ごとに","で区切って表します。

In [70]:
x = np.array([[1,2,3],[4,5,6]])
x[1,2]

6

In [71]:
x = np.array([[1,2,3],[4,5,6]])
x[0,1]

2

2.10.4 要素の書き換え

行も列もインデックスは0から始まることに注意してください。要素の書き換えは、
ベクトルのときと同様、以下のように記述します。

In [72]:
x = np.array([[1,2,3],[4,5,6]])
x[1,2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


In [73]:
x = np.array([[1,2,3],[4,5,6]])
x[0,1]=100
print(x)

[[  1 100   3]
 [  4   5   6]]


2.10.5 要素が0や1のndarrayの作成

すべての要素が0のndarrayは、np.zeros(size)で作ることができます。以下のようにすれば、長さ10のベクトルが生成されます。

In [74]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


また、size=(2,10)とすれば、要素がの2×10の行列が生成されます。成

In [75]:
print(np.zeros((2,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


sizeはtuple型です。sizeを(2,3,4)などとすれば、2×3×4の3次元配列が生成されます。何次元でも生成可能です。すべての要素を0ではなく1にしたい場合には、np.ones(size)を使います。

In [76]:
print(np.ones((2,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [77]:
print(np.ones((4,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


2.10.6 要素がランダムな行列の生成

要素がランダムな行列を生成する場合には、np.random.rand(size)が使えます。
各要素を0〜1の一様分布から生成した行列が生成されます。この場合のsize
tupleではないということに注意してください。例えば、2×3の乱数行列を生す
るには、以下のように記述します(ランダムな行列が作成されますので実行すに数値は変わります）。るたび

In [78]:
np.random.rand(2,3)

array([[0.40212183, 0.95977891, 0.31602191],
       [0.81524216, 0.66091057, 0.13920311]])

In [79]:
np.random.rand(4,2)

array([[0.67430719, 0.94885005],
       [0.18435409, 0.31154669],
       [0.70596817, 0.34792601],
       [0.85194   , 0.00883893]])

np.random.rand((2,3))のようにするとエラーが出てしまいます。
np
.random.randn(size)を使うと、平均0分散1のガウス分布から乱数が生成
できますた、た、np.random.randint(low, high, size)を使うlowからhi、
ghまでのランダムな整数値からなるsizeの大きさの行列できます。を生成

2.10.7 行列のサイズの変更

行列のサイズを変更したい場合には、変数名.reshape(n,m)を使います。以下のベクトルのサイズを変えてみましょう。

In [80]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


例えば、2×5の行列に変更するには、以下のように記述します。

In [81]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? 
Nothing done.


In [83]:
a = np.arange(3,9)
print(a)

[3 4 5 6 7 8]


In [84]:
a.reshape(3,2)

array([[3, 4],
       [5, 6],
       [7, 8]])

# 2.11 行列（ndarray）の四則演算

2.11.1 行列における四則演算

四則演算+、-、*、/は、対応する要素ごとに行われます。例えば、以下のように
入力して確認してください。

In [85]:
x = np.array([[4,4,4],[8,8,8]])
y = np.array([[1,1,1],[2,2,2]])
print(x + y)

[[ 5  5  5]
 [10 10 10]]


In [86]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,1,1],[1,2,3]])
print(x - y)

[[0 1 2]
 [3 3 3]]


2.11.2 スカラー ✕ 行列

スカラーを行列に掛けると、以下のようにすべての要素に作用します。

In [87]:
x = np.array([[4,4,4], [8,8,8]])
print(10 * x)

[[40 40 40]
 [80 80 80]]


In [88]:
x = np.array([[1,2,3],[4,5,6]])
print(20 * x)

[[ 20  40  60]
 [ 80 100 120]]


2.11.3 算術関数

numpyには、様々な算術関数が用意されています。例えば、第4章で解説する
exp(x)は、以下のように計算できます。

In [89]:
x = np.array([[4,4,4], [8,8,8]])
print(np.exp(x))

[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]


In [90]:
x = np.array([[2,4,6],[8,10,12]])
print(np.exp(x))
print(np.sqrt(x))
print(np.log(x))
print(np.round(x,3))
print(np.mean(x))
print(np.std(x))
print(np.max(x))
print(np.min(x))

[[7.38905610e+00 5.45981500e+01 4.03428793e+02]
 [2.98095799e+03 2.20264658e+04 1.62754791e+05]]
[[1.41421356 2.         2.44948974]
 [2.82842712 3.16227766 3.46410162]]
[[0.69314718 1.38629436 1.79175947]
 [2.07944154 2.30258509 2.48490665]]
[[ 2  4  6]
 [ 8 10 12]]
7.0
3.415650255319866
12
2


これもすべての要素に作用します。それ以外にも、平方根np.sqrt(×)、対数np.log(x)、四捨五入np.round(x,有効桁数)などがあります。
また、すべての要素に対して1つの数値を返す、平均np.mean(x)、標準偏差np.std(x)、最大値np.max(x)、最小值np.min(x)などもあります。

2.11.4 行列積の計算

要素ごとでは計算できない行列積はどうやって計算するのでしょうか?　これについては、第4章でも解説しますので、ここでは結論だけを述べると変数名1.dot(変数名2)で計算できます。

In [91]:
v = np.array([[1,2,3],[4,5,6]])
w = np.array([[1,1], [2,2], [3,3]])
print(v.dot(w))

[[14 14]
 [32 32]]


In [92]:
v = np.array([[10,9,8],[7,6,5]])
w = np.array([[1,2],[3,4],[5,6]])
print(v.dot(w))

[[ 77 104]
 [ 50  68]]


# 2.12 スライシング

2.12.1 スライシングの利用

listとdarrayでは、要素をいっぺんに表すスライシングという便利な方法があり、これを使いこなすとプログラムが楽になります。スライシングは":"を使って表します。列えば、以下のように、変数名[:n]で、0から-1まで要素を一度に参照することができます。

In [93]:
x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [94]:
x = np.arange(20)
print(x[:9])

[0 1 2 3 4 5 6 7 8]


変数名[n:]とすると、nから最後の要素までが参照されます。

In [95]:
print(x[5:])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [96]:
print(x[9:])

[ 9 10 11 12 13 14 15 16 17 18 19]


変数名[n1:n2]とすると、n1からn2-1の要素までが参照されます。

In [97]:
print(x[3:8])

[3 4 5 6 7]


In [98]:
print(x[5:18])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17]


変数名[n1:n2:dn]とすると、n1からn2-1の要素まで、dnおきで参照されます。

In [99]:
print(x[3:8:2])

[3 5 7]


In [100]:
print(x[4:18:3])

[ 4  7 10 13 16]


以下のようにすると、配列の順番が逆向きになります。

In [101]:
print(x[::-1])

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [102]:
print(x[::-1])

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


スライシングは、1次元以上のlistやndarrayでも使えます。

In [103]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
print(y[:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


In [104]:
x = np.array([[1,3,5],[2,4,6],[3,5,7]])
print(x[:2, 0:2])

[[1 3]
 [2 4]]


# 2.13 条件を満たすデータの書き換え

2.13.1 bool配列の利用

numpyでは、行列に収められたデータから、ある条件に合うものだけを簡単に抽出し、書き換えることができます。
以下のように×を定義し、×>3とすると、その結果のTrueかFalseのbool型の配列が返されます。

In [105]:
x = np.array([1, 1, 2, 3, 5, 8, 13])
x > 3

array([False, False, False, False,  True,  True,  True])

In [106]:
x = np.array([0, 1, 2, 4, 6, 8])
x > 2

array([False, False, False,  True,  True,  True])

このbool配列で、配列の要素を参照すると、以下のようにTrueの要素のみが出力
されます。

In [107]:
x[x > 3]

array([4, 6, 8])

In [108]:
x[x > 4]

array([6, 8])

x>3を満たす要素だけを、999に変えるには以下のようにします。

In [109]:
x[x > 3] = 999
print(x)

[  0   1   2 999 999 999]


# 2.14 Help

2.14.1 Helpの利用

関数には非常に多くの種類があり機能も多様ですので、help(関数名)で関数の説明文
が表示されることを知っていると便利です。同じ関数でも、引数省略できたりと使
い方のバリエーションが様々で、なかなかすべての機能を覚ことはできなと
いからです。例えば、以下のように入力して、確認できます。

In [110]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer t

In [111]:
help(np.random.randint(5))

Help on int object:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Built-in subclasses:
 |      bool
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |

In [112]:
help(np.random.randint(5,10,(3,2)))

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

ここから、例えば、np.random.radient(5)とすると、0〜4までの整数の乱数が1
つ生成されるこ、、np.random.randint(5,10,(3,2))とすば、
整数の乱数を成分に持つ3×2の行列が生成されること、などの使方がわかり ります。

# 2.15 関数

2.15.1 関数の利用

プログラムの一部を関数としてまとめることができます。何度も使う繰り返しのコードは関数数にしてしまうと便利です。本書でも関数を多用します。関数、def 関数名():O:から始まり、その内容をインデントして記述し定義しま実行は、関数名()た
名()です。

In [113]:
def my_func1():
    print('Hi!')
# 関数 my_func1()の定義はここまで
my_func1() #関数を実行

Hi!


In [114]:
def my_func2():
    print('Hello!')
my_func2()

Hello!


In [115]:
def func_3():
    print('Good bye')
func_3()

Good bye


関数に値a、bを渡したい場合には、def 関数名(a,b):のようにします。出力したい場合合には、returnの後にその変数名を書きます。例えば、以下のよになります。ぃ

In [116]:
def my_func2(a, b):
    c = a + b
    return c


my_func2(1, 2)

3

In [117]:
def my_func4(a,b,c):
    d = (a - b) * c
    return d
my_func4(1,2,3)

-3

In [118]:
def my_func5(a,b,c,d):
    e = a + b * c / d
    return e
my_func5(1,2,3,4)

2.5

2.15.2 引数と戻り値

関数に渡す変数を引数(ひきすう)と言います。関数の出力を戻り値と言います。
ど
んな型でも引数や戻り値にできます。また戻り値も複数定義できす。例えば、何
らかのデータを1次元のndarray型で関数に渡して、その平均標準偏差を出標 力する関数を作ります。

In [119]:
def my_func3(D):
    m = np.mean(D)
    s = np.std(D)
    return m, s

In [120]:
def my_func3(D):
    m = np.mean(D)
    s = np.std(D)
    return m, s

np.mean(D)、np.std(D)はnumpyで定義される関数で、Dの平均と標準偏差を
出力します。複数の出力は、return m,sと変数間を","で区切って記述します。
乱数のデータを準備して、この関数を使い、結果を表示してみましょう。乱数のす
で実行のたびに結果は変わります。

In [121]:
data=np.random.randn(100)
data_mean, data_std = my_func3(data)
print('mean:{0:3.2f}, std:{1:3.2f}'.format(data_mean, data_std))

mean:-0.06, std:0.98


In [122]:
data=np.random.randn(100)
data_mean, data_std = my_func3(data)
print('mean:{0:3.2f}, std:{1:3.2f}'.format(data_mean, data_std))

mean:0.02, std:1.10


複数の戻り値の受け取り方は、data_mean,data_std = my_func3(data)と、","で区切って記述します。
戻り値直が複数でも、1つの変数で受けることができます。この場合戻り値はtup
le型となり、それぞれの要素に関数の戻り値が格納されます。乱数ので実行のたびに結果は変わります。です

In [123]:
output = my_func3(data)
print(output)
print(type(output))
print('mean:{0:3.2f}, std:{1:3.2f}'.format(output[0], output[1]))

(0.015102434804341919, 1.0977531811342722)
<class 'tuple'>
mean:0.02, std:1.10


In [126]:
output = my_func3(data)
print(output)
print(type(output))
print('mean:{0:3.2f}, std:{1:3.2f}'.format(output[0], output[1]))

(-0.402491673407156, 0.9655870610920702)
<class 'tuple'>
mean:-0.40, std:0.97


# 2.16 ファイル保存

2.16.1 1つのndarry型の保存

1つのndarray型をファイルに保存するには、p.save('ファイル名.npy', 変数名)を使います。ファイルの拡張子は、.npyです(乱数ですので実行のたびに結果は変わります)。

In [124]:
data = np.random.randn(5)
print(data)
np.save('datafile.npy', data)  # セーブ
data = []                      # データの消去
print(data)
data = np.load('datafile.npy') # ロード
print(data)

[ 1.41593648 -0.78320973 -0.39875053 -0.83059139 -1.4158432 ]
[]
[ 1.41593648 -0.78320973 -0.39875053 -0.83059139 -1.4158432 ]


In [127]:
data = np.random.randn(5)
print(data)
np.save('datafile.npy', data)  # セーブ
data = []                      # データの消去
print(data)
data = np.load('datafile.npy') # ロード
print(data)

[ 0.76954066  0.31671557 -0.1098119   0.45021091  0.74646588]
[]
[ 0.76954066  0.31671557 -0.1098119   0.45021091  0.74646588]


読み出しは、np.load('ファイル名.npy')です。

2.16.2 複数のndarray型の保存

複数のndarray型を保存するには、np.savez('ファイル名.npz', 変数名1=変数名1, 変数名2=変数名2,⋯)を使います。

In [125]:
data1 = np.array([1,2,3])
data2 = np.array([10,20,30])
np.savez('datafile2.npz', data1=data1, data2=data2) # セーブ
data1 = [] # データの消去
data2 = []
outfile = np.load('datafile2.npz') # ロード
print(outfile.files) # 格納しているデータの表示
data1 = outfile['data1'] # data1の取り出し
data2 = outfile['data2'] # data2の取り出し
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]


データをnp.loadでロードすると、保存したすべての変数がoutfile に格納され、outf
ile'"変数'名]によって、それぞれの変数を参照するこができます。
outfi
le.filesで格納してある変数のリストを見ることきます。pz"

In [128]:
data1 = np.array([1,2,3])
data2 = np.array([10,20,30])
np.savez('datafile2.npz', data1=data1, data2=data2) # セーブ
data1 = [] # データの消去
data2 = []
outfile = np.load('datafile2.npz') # ロード
print(outfile.files) # 格納しているデータの表示
data1 = outfile['data1'] # data1の取り出し
data2 = outfile['data2'] # data2の取り出し
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]


# うるう年判定プログラム

In [135]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? 
Nothing done.


In [140]:
if __name__ == "__main__":

    # 値を入力させる
    input_num = input("西暦年を入力して下さい：")
    year = int(input_num)

    # 条件式に従い、閏年の判定を行う
    if year%4==0:
        if year%100==0:
            if year%400==0:
                print("{}年は閏年です。".format(year))
            else:
                print("{}年は閏年ではありません。".format(year))
        else:
            print("{}年は閏年です。".format(year))
    else:
        print("{}年は閏年ではありません。".format(year))

西暦年を入力して下さい：2000
2000年は閏年です。


In [139]:
if __name__ == "__main__":

    # 値を入力させる
    input_num = input("西暦年を入力して下さい：")
    year = int(input_num)

    # 条件式に従い、閏年の判定を行う
    if year%400==0 or ( year%4==0 and year%100!=0 ):
        print("{}年は閏年です。".format(year))
    else:
        print("{}年は閏年ではありません。".format(year))

西暦年を入力して下さい：2020
2020年は閏年です。


・完成版

In [144]:
def is_leap_year(year):
    if year % 400 == 0:
        return True
    elif year % 100 == 0:
        return False
    elif year % 4 == 0:
        return True
    else:
        return False

print(is_leap_year(2021))

False


# 線形連立方程式を解くプログラム

In [146]:
def dainyu_kai(a, b, c, d, A1, A2):
  determinant = a * d - b * c
  if determinant != 0:
    x = (A1 * d - A2 * b) / (a * d - c *b)
    y = (A1 * c - A2 * a) / (b * c - d * a)
    print(x, y)
  else:
    if c/a == A1 / A2:
      print('解が複数存在します')
    else:
      print('解が存在しません')

In [147]:
import numpy as np
 
# 係数行列とベクトルの用意
A = np.array([[4,  3,  2],
              [2, -1, -2],
              [1,  5,  6]])
 
b = np.array([4, 2, 3])
 
# 求解
x = np.linalg.solve(A, b)
print(f"x = {x}")
# x = [ 3. -6.  5.]

x = [ 3. -6.  5.]
